<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['system_report_app_description'] = 'The System Report provides information on the operating system and underlying hardware.';
$lang['system_report_app_name'] = 'System Report';
$lang['system_report_available'] = 'Available';
$lang['system_report_cpu_model'] = 'CPU Model';
$lang['system_report_filesystem'] = 'Filesystem';
$lang['system_report_filesystem_summary'] = 'Filesystem Summary';
$lang['system_report_item'] = 'Item';
$lang['system_report_kernel_version'] = 'Kernel Version';
$lang['system_report_load'] = 'Load';
$lang['system_report_memory_size'] = 'Memory Size';
$lang['system_report_mounted'] = 'Mounted';
$lang['system_report_size'] = 'Size';
$lang['system_report_system_details'] = 'System Details';
$lang['system_report_system_time'] = 'System Time';
$lang['system_report_use'] = 'Use %';
$lang['system_report_used'] = 'Used';
$lang['system_report_value'] = 'Value';
