<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['system_report_app_description'] = 'Системный отчет предоставляет информацию об операционной системе и используемом оборудовании.';
$lang['system_report_app_name'] = 'Системный отчет';
$lang['system_report_available'] = 'Доступен';
$lang['system_report_cpu_model'] = 'Модель процессора';
$lang['system_report_filesystem'] = 'Файловая система';
$lang['system_report_filesystem_summary'] = 'Сводка файловой системы';
$lang['system_report_item'] = 'Пункт';
$lang['system_report_kernel_version'] = 'Версия ядра';
$lang['system_report_load'] = 'Нагрузка';
$lang['system_report_memory_size'] = 'Объем памяти';
$lang['system_report_mounted'] = 'Установлено';
$lang['system_report_size'] = 'Объем';
$lang['system_report_system_details'] = 'Детали системы';
$lang['system_report_system_time'] = 'Системное время';
$lang['system_report_use'] = 'Занято %';
$lang['system_report_used'] = 'Занято';
$lang['system_report_value'] = 'Значение';
