<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['system_report_app_description'] = 'Raporty systemowe dostarczają informacji o systemie operacyjnym oraz sprzęcie.';
$lang['system_report_app_name'] = 'Raporty systemowe';
$lang['system_report_available'] = 'Dostępne';
$lang['system_report_cpu_model'] = 'Model CPU';
$lang['system_report_filesystem'] = 'System plików';
$lang['system_report_filesystem_summary'] = 'Podsumowanie systemu plików';
$lang['system_report_item'] = 'Element';
$lang['system_report_kernel_version'] = 'Wersja jądra';
$lang['system_report_load'] = 'Obciążenie';
$lang['system_report_memory_size'] = 'Rozmiar pamięci';
$lang['system_report_mounted'] = 'Zamontowane';
$lang['system_report_size'] = 'Rozmiar';
$lang['system_report_system_details'] = 'Szczegóły systemu';
$lang['system_report_system_time'] = 'Czas systemowy';
$lang['system_report_use'] = 'Używane w %';
$lang['system_report_used'] = 'Używane';
$lang['system_report_value'] = 'Wartość';
